[package]
name = "harbor-cli"
version = "0.5.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
harbor-core = { path = "../core" }
serde_yaml = "0.9.34"
serde_json = "1.0.132"
winreg = "0.52.0"
